module AbiCoderRb
  class AbiTokenizer
    @abi: String
    @index: Integer

    def initialize: (String) -> void
    def next_token: -> String

    private

    def read_identifier: -> String

    def skip_whitespace: -> void
  end
end